### ISSUE TITLE
hierarchy and inheritance problem

### ISSUE THREAD

**Issue by matantsu** [GoogleCloudPlatform/endpoints-proto-datastore#125]
I want to create a User class with subclasses (eg: Reader) so i created the following:

models.py
```
class User(EndpointsModel):
   type = ndb.StringProperty()

class Reader(User):
   type = 'Reader'
   reader_prop = 'secret'
```

api.py
```
@Reader.method(path='reader/path',
                              name='reader.path',
                              http_method='GET',
                              request_message=message_types.VoidMessage)
    def getReader(self, unused):
        # gets current User
        me = methods.me(self.request_state)
        if me.type == 'Reader':
            return me
        else:
            endpoints.UnauthorizedException(config.messages['this method is for READERs only !'])
```

throws: `expected response type <class '.Reader'>, sent <class '.User'>`

but Reader is a subclass of User , it should be good.

is this a problem with the library or in my thinking ?

**Comment by dhermes** [comment]
You made a `Reader.method`.

So your have

```python
>>> my_user = User()
>>> isinstance(my_user, Reader)
True
>>> my_reader = Reader()
>>> isinstance(my_reader, User)
False
```

In other words, inheritance goes in the wrong direction for `getReader` to return a `User` object.

This means `methods.me` should return a `Reader`.

Am I missing something else?

**Comment by matantsu** [comment]
`methods me` returns the current user , which can be a `Reader` or some other subclass of user. so it does a `User.get_by_id` to get the current user , when i construct a `Reader` entity and perform `methods.me` it does return the entity.

in the API , i make sure that this `User` is a 'Reader' , so i should be able to return it because it IS a reader.

**Comment by dhermes** [comment]
Yes I understand that, but `User.get_by_id` will only return instances of type `User`. Since you decorate the `getReader` method with `@Reader.method`, the return type must be a `Reader`.

Since you've checked that `me.type == 'Reader'`, you can just cast the `me` instance to a `Reader` object.

(You can check the type in your logs by `logging.info(type(me))` before trying to `return me`)

--------

**NOTE 1**: Since `Reader` is a **subclass** of `User`, instances of `User` are not recognized as instances of `Reader` (but in the opposite direction, instances of `Reader **are** recognized as instances of `User`). For example:

```python
>>> class User(object): pass
... 
>>> class Reader(User): pass
... 
>>> u = User()
>>> isinstance(u, Reader)
False
>>> r = Reader()
>>> isinstance(r, User)
True
```

--------

**NOTE 2**: When you overwrite the `type = ndb.StringProperty()` property on `User` with `type = 'Reader'`, it is no longer a datastore property, it is just a string

--------

**NOTE 3**: Using `type` is dangerous because it is a builtin in `python`, e.g.

```python
>>> type(1337)
<type 'int'>
```

This may be causing confusion about what the actual type of your `User` objects is?

**Comment by matantsu** [comment]
thanks for the reply , fiddling around a bit I found the class `PolyModel` which according to google is used in exactly in cases like this.

can i use this class with multiple inheretence like `class A(EndpointsModel , PolyModel)` and if not , is there an implementation of this class in the library ?

additionally , excuse me for my little knowledge in python , my first instinct when approaching this problem was casting , but searching the web , people said that python doesn't have casting as it's a dynamically typed language.

if casting *IS* available as an option , which way is correct to solve this problem (casting or `PolyModel`)? 

thx in advance :)

**Comment by dhermes** [comment]
Simplest answer: You don't need a `Reader` class, just store the secret data in an entity with `type == 'Reader'` and be done.

------

RE: Casting, you can simple take your `User` object (called `me`) and create a `Reader`:

```python
me_reader = Reader(type=me.type, key=me.key, ...)
```

------

As for `polymodel`, it's totally overkill for what you're trying to do.

If you ever need it, we don't support it but #28 provides a complete sample of how to use it.

------

I'm going to close this issue out since it doesn't actually involve library issues.
