### ISSUE TITLE
Path arguments for ancestors break

### ISSUE THREAD

**Issue by lukegr** [GoogleCloudPlatform/endpoints-proto-datastore#135]
Hello. When building an API with nested entities (e.g., grandparent/parent/child), the variable `_child` returns '*None*' (set on line 94) seemingly at random, this breaks `ndb.Key` on lines 138 and 142 and causes `BadArgumentError: Incomplete Key entry must be last`. Adding a `greatGrandparent` seems to break the `_child` variable permanently while the `_parent` remains somewhat unpredictable.

I've just added the log to the [Gist](https://gist.github.com/lukegr/840c7a4b4f3cbe5c3a2c).

Thanks.

**Edit:** I've just read through your update on Stackoverflow but I don't understand completely. Here's the `set_key` method in `ParentModel`:

```python
def set_key(self):
        if self._grandparent is not None and self._parent is not None:
            key = ndb.Key(GrandparentModel, self._grandparent, ParentModel, self._parent)
            self.UpdateFromKey(key)
```

and in `ChildModel`:

```python
def set_key(self):
        if self._grandparent is not None and self._parent is not None and self._child is not None:
            key = ndb.Key(GrandparentModel, self._grandparent, ParentModel, self._parent, ChildModel, self._child)
            self.UpdateFromKey(key)
```

How should I be doing this differently so I don't depend on the order that the variables are set? I'm also a little confused as to why you mentioned the exception on [line 136](https://gist.github.com/lukegr/840c7a4b4f3cbe5c3a2c#file-main-py-L136).

Thank you for your in-depth explanations, I really appreciate it.

**Comment by dhermes** [comment]
So you call `ChildModel.set_key` from `ChildModel.set_grandparent`, `ChildModel.set_parent` and `ChildModel.set_child`.

However, in `ChildModel.set_parent` you assume `grandparent` is already set before calling `set_key`:

```python
    def set_parent(self, value):
        if not isinstance(value, basestring):
            raise TypeError('Parent name must be a string.')

        self._parent = value

        logging.warning('Check _grandparent value: %s' % self._grandparent)
        logging.warning('Check _parent value: %s' % self._parent)

        if self._grandparent is None:
            raise Exception('set_parent: self._grandparent is None')
```

This is the out of order assumption that breaks your app. You will do that `self._grandparent is None` check in `ChildModel.set_key` every time and eventually set the key.

The reason it isn't getting set is because the check

```python
    def set_key(self):
        if (self._grandparent is not None and
                self._parent is not None and
                self._child is not None):
            key = ndb.Key(GrandparentModel, self._grandparent,
                          ParentModel, self._parent,
                          ChildModel, self._child)
            self.UpdateFromKey(key)
```

will **never** pass with the two methods you have implemented

```python
    @ChildModel.method(
        name='insert',
        path='grandparent/{grandparent}/parent/{parent}/child')
    def child_insert(self, child):
        child.put()
        return child

    @ChildModel.query_method(
        name='list',
        path='grandparent/{grandparent}/parent/{parent}/child',
        query_fields=('grandparent', 'parent',))
    def child_list(self, query):
        return query
```

since neither one will set `_child`. Those are (very likely) the right inputs in both methods, but for the first, you want an incomplete key to have the backend set it and for the second you just want the ancestor key `Key(GrandParent, foo, Parent, Bar)` and then you want to do an ancestor query.

You could get around the first (auto-assigned ID) by allowing `_child` to be `None` in `set_key`.

----

Also, on StackOverflow you should mark my answer as accepted in addition to the upvote :grinning:

**Comment by lukegr** [comment]
I updated the [Gist](https://gist.github.com/lukegr/840c7a4b4f3cbe5c3a2c). I'm not sure I have the best solution, so maybe something can be worked out there. What do you think about updating the ancestor example with a third nested entity?

**Comment by dhermes** [comment]
-   I don't think adding another ancestor will clarify the example. The core issue was that we don't know the order of the ancestor components so any of them (if two, or three, or N) can set the key once everything is in place
-   As you pointed out, this doesn't really cover your case where you want only ancestors for `query_method`s. You have two sort of options

    1. Use a separate property to accomplish a similar goal
    1. Muck around with `self._endpoints_query_info._AddFilter` and try to detect if the value is being set via a query or via `method`
