### ISSUE TITLE
Datetime weirdness

### ISSUE THREAD

**Issue by 8enmann** [GoogleCloudPlatform/endpoints-proto-datastore#83]
First off, great job on this library. Love the simplicity.

This could be my own stupidity, but I set up a DatetimeProperty in my model and am using the JS API to send the JS object. Unfortunately I get the following error:

```
utils.py, line 330, in DatetimeValueFromString
    raise TypeError('Could not deserialize timestamp: %s.' % (value,))
TypeError: Could not deserialize timestamp: 2013-10-31T23:34:34.529Z.
```

It appears to be failing because of the trailing Z in the timestamp. Is there an easy workaround? I tried adding a Z to DATETIME_STRING_FORMAT and it fixed the problem, but I'd prefer a more elegant solution so I don't have to break other users of this library who may be depending on the existing behavior.

**Comment by Bekt** [comment]
This is kind of annoying since different clients might send date in different formats. Can we let [dateutil](https://pypi.python.org/pypi/python-dateutil/2.4.0) handle parsing in [DatetimeValueFromString](https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/88ad7f5f8df15f414a80171136580eb79a3efb90/endpoints_proto_datastore/utils.py#L302)?

Some examples: https://dateutil.readthedocs.org/en/latest/examples.html#parse-examples

Was gonna submit a PR but wasn't sure on about your policy on third-party libraries.

**Comment by dhermes** [comment]
@Bekt If you look at the [spec][1] for discovery documents, date and date-time are single formats (via RFC3339): `YYYY-MM-DD` and `YYYY-MM-DDThh:mm:ss.fffZ`.

So if some of your clients don't use that format, it's not a valid `date-time` in a discovery based API. 

If it's **necessary** to allow multiple clients to use other formats, than just using a `string` property would be an easy way to address this.

Are there difficulties on Android, iOS or Javascript with getting times in RFC3339 format? Some other platform I'm not thinking of?

[1]: https://developers.google.com/discovery/v1/type-format

**Comment by Bekt** [comment]
I am okay with sticking to the RFC3339 format. However, [`DATETIME_STRING_FORMAT`](https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/88ad7f5f8df15f414a80171136580eb79a3efb90/endpoints_proto_datastore/utils.py#L22) does not conform to RFC3339 as there can be a `Z` at the end of the string. I think it's better to introduce this change instead of monkey-patching.

**Comment by dhermes** [comment]
I agree. Now that you mention it (I had forgotten) `endpoints-proto-datastore` doesn't support `date-time` the way it should (see #6). So in addition to adding the `Z` we need to actually support it the way it's meant to be done (this is mostly outline in #6).

This is because when I originally wrote it (spring 2013, when I was still at Google), the `protorpc` library didn't support it.

However, as @sstriker's [comment][1] indicates, it should be possible to use `protorpc.messages.DateTimeField` instead.

[1]: https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/issues/6#issuecomment-21650334

**Comment by Bekt** [comment]
Thanks for the background info.

I take it you're not with Google anymore? If that is the case I wonder if this project is still seriously maintained as there seem to be a lot of inconsistency between ndb.Model, protorpc.messages, and EndpointsModel.

**Comment by dhermes** [comment]
@Bekt I still chase down and squash reported bugs. Also I still "work" for Google (see https://github.com/GoogleCloudPlatform/gcloud-python) I'm just not full-time there.

I'd love to hear about the inconsistencies and try to improve them.

Note that `EndpointsModel` directly [inherits][1] from `ndb.Model` so hopefully there isn't inconsistency between those two.

As for `protorpc.messages`, I'd love to hear what you expect / what seems broken / what is confusing. (FWIW the goal was for the majority of users to just never worry about `protorpc` and use this like they use `ndb`, so consistency between the two didn't seem relevant.)

[1]: https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/deecf33600212bb7c51dfbddec58d19539daf36d/endpoints_proto_datastore/ndb/model.py#L590

**Comment by Bekt** [comment]
Awesome, thanks for the response @dhermes.

I will report some of the issues I've ran into in the past couple of weeks and let you know when I get a chance.

**Comment by dhermes** [comment]
Awesome! Happy to have you as a user AND filing bugs. Feedback is great!
